export const opcodes = {
  NOP: 0x00,
  LOADA: 0x01,
  LOADB: 0x02,
  STOREA: 0x03,
  STOREB: 0x04,
  ORA: 0x05,
  ORB: 0x06,
  ANDA: 0x07,
  ANDB: 0x08,
  XORA: 0x09,
  XORB: 0x0A,
  NOTA: 0x0B,
  NOTB: 0x0C,
  SHLA: 0x0D,
  SHLB: 0x0E,
  SHRA: 0x0F,
  SHRB: 0x10,
  JUMP: 0x11,
  JZA: 0x12,
  JZB: 0x13,
  ADDA: 0x14,
  ADDB: 0x15,
  PUSH: 0x17,
  POP: 0x18,
  CALL: 0x19,
  RET: 0x1A,
  SETBP: 0x1B,
  LOADABP: 0x1C,
  STOREABP: 0x1D,
  END: 0xFF,
};

export const opcodesParams = {
  [opcodes.NOP]: 0,
  [opcodes.LOADA]: 1,
  [opcodes.LOADB]: 1,
  [opcodes.STOREA]: 1,
  [opcodes.STOREB]: 1,
  [opcodes.ORA]: 1,
  [opcodes.ORB]: 1,
  [opcodes.ANDA]: 1,
  [opcodes.ANDB]: 1,
  [opcodes.XORA]: 1,
  [opcodes.XORB]: 1,
  [opcodes.NOTA]: 0,
  [opcodes.NOTB]: 0,
  [opcodes.SHLA]: 1,
  [opcodes.SHLB]: 2,
  [opcodes.SHRA]: 1,
  [opcodes.SHRB]: 1,
  [opcodes.JUMP]: 1,
  [opcodes.JZA]: 1,
  [opcodes.JZB]: 1,
  [opcodes.ADDA]: 1,
  [opcodes.ADDB]: 1,
  [opcodes.PUSH]: 1,
  [opcodes.POP]: 1,
  [opcodes.CALL]: 1,
  [opcodes.RET]: 0,
  [opcodes.SETBP]: 1,
  [opcodes.LOADABP]: 1,
  [opcodes.STOREABP]: 1,
  [opcodes.END]: 0,
};

export default opcodes;
